### ISSUE TITLE
Yazelix does not start in current directory

### ISSUE THREAD

**Issue by Pierre-Thibault** [luccahuguet/yazelix#340]
When I start yazelix:

`nu ~/.config/yazelix/nushell/scripts/core/start_yazelix.nu`

It starts at `~/.config/yazelix`.

I expected to start at the current directory of my shell.

**Comment by luccahuguet** [comment]
@Pierre-Thibault 

i fixed this! thanks for creating this issue

you can git pull now

im closing this, if you need you can re-open

**Comment by Pierre-Thibault** [comment]
I cannot reopen the issue.

I pulled the changes and I still have the same behaviour.

**Comment by Pierre-Thibault** [comment]
I did a pull. I am still experiencing the same behaviour.
